package enums.etc;

public enum ServerActionEnum {
	JOIN_SUCCESS,
	JOIN_FAIL,
	JOIN_CERTIFICATION,
	LOGIN_SUCCESS,
	LOGIN_FAIL_INPUT_ERROR,
	LOGIN_FAIL_OVERLAP_ACCEPT,
	LOGIN_NEW_USER,
	WAITING_ROOM_ENTER,
	GAME_CREATEROOM_SUCCESS,
	GAME_CREATEROOM_FAIL,
	GAME_ROOM_ADD;
	

}
