package enums.etc;

public enum UserPositionEnum {
	POSITION_LOGIN,
	POSITION_WAITING_ROOM,
	POSITION_JOIN,
	POSITION_FIND_ID,
	POSITION_FIND_PW,
	POSITION_FIND_PW_EMAIL,
	POSITION_GAME_ROOM,
	POSITION_STORE,
	POSITION_MODIFY_MY_INFO,
	POSITION_EXIT;
}
